const VILLAGE_GROWTH_RATE = 1;
const VILLAGE_GROWTH_RATE_UPGRADE_VALUE = 1;
const VILLAGE_POPULATION_CAP = 100;
const ARMY_LINE_WIDTH = 5;

const GROWTH = "VILLAGE_GROWTH_RATE";
const CAP    = "VILLAGE_POPULATION_CAP";

const UPGRADE_TARGETS = [
    GROWTH,
    CAP
];